### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by KaoutarIdr** [evolv34/graphite-kafka-connect#8]
Hello @evolv34 

i'm working with your connector, when i run it it works but when i write something in the topic i become the following Exception

![image](https://user-images.githubusercontent.com/25535797/40971008-868b4206-68bc-11e8-82d3-aedbd689ef88.png)
 i am sending JSON data. Hope you can help me 
Thank you

**Comment by evolv34** [comment]
Hi @kawi3,

Could you share the json you are writing to the topic ?! It would've helpful for me to debug.

Thank you

**Comment by KaoutarIdr** [comment]
i'm sending sensordata like {"Temperature:25, "Humidity":30}

thank you for your answer

**Comment by evolv34** [comment]
Thank you @kawi3. Can you please change message format to match this https://github.com/evolv34/graphite-kafka-connect/blob/master/src/main/resources/sample-metric.json ?!

**Comment by evolv34** [comment]
Let me know if it still throws any exception. Also "tags" in the json are optional.

**Comment by KaoutarIdr** [comment]
Hi @evolv34 i just used the format you told me but it didn't work either i still get the same Exception
Thank you

**Comment by evolv34** [comment]
Let me take a look at it. Can you paste the code snippet that produces the above format ?! Are you producing the messages from console producer or from code ?!

**Comment by KaoutarIdr** [comment]
I tried with the exact message u gave me: 
{
  "metricName": "sample.metric.name",
  "tags": {
    "tag1": "value"
  },
  "value": "123456"
}
and i am producing the messages from console not from code

**Comment by evolv34** [comment]
Thanks let me test it and keep you posted.

**Comment by evolv34** [comment]
Give me a day I will look into it and fix it.

**Comment by KaoutarIdr** [comment]
Thank you so much

**Comment by evolv34** [comment]
Hi @kawi3,

Are you using avro message or json message ? I have checked with the work steps I followed from README.MD file. Could you please follow the steps below ?
run `sbt build-complete` to create uber jar.
run `docker-compose -f docker/docker-compose.yml up`
add `broker` to `etc/hosts` file.
and post the following message.
`{"metricName":"sample.metric.name","tags":{"tag1":"value"},"value":"123456"}`
This one works fine.

Can you please let me know the steps to reproduce the issue you are facing. It would be helpful.

Thanks

**Comment by KaoutarIdr** [comment]
Hi @evolv34 , 
I am using a json message and JSON Converter. I did create the jar with sbt build-complete but i didn't work with the docker because i'm using the confluent Plattform! after creating the jar file i did run the connector with the following command: bin/connect-standalone /etc/kafka/connect-standalone.properties  /etc/kafka/kafka-connect-graphite.properties, until here everything works 
![image](https://user-images.githubusercontent.com/25535797/41022643-7dfc2994-696a-11e8-9f33-b4a50d399e7d.png)
Then i start producing messages from console producer 
![image](https://user-images.githubusercontent.com/25535797/41022818-f8451b02-696a-11e8-8a9d-24f49248a2b2.png)
after producing the message i become the Exception i already mentioned 

Thank you so much for your help

**Comment by evolv34** [comment]
Thank you. I will test it and let you know. Also are you using confluent platform 4.0.0 ?!

**Comment by KaoutarIdr** [comment]
Thank you so much, i'm using the last version 4.1.1

**Comment by evolv34** [comment]
Hi @kawi3,

I was able to reproduce the issue. The issue is fixed. I have added `key.converter` and `value.converter` to `kafka-connect-graphite.properties` file. It works fine. I have tested it on 4.1.1.

Please update `kafka-connect-graphite.properties` at your end. 
Ref: https://github.com/evolv34/graphite-kafka-connect/blob/master/src/main/resources/kafka-connect-graphite.properties#L21-L22

Let me know if you are seeing more issue.

**Comment by KaoutarIdr** [comment]
Hi @evolv34 

I just tested it and it works, thank you so much for your help

**Comment by evolv34** [comment]
Hi @kawi3,

No problem.
